### ISSUE TITLE
override file invalid

### ISSUE THREAD

**Issue by pschulzk** [gentics/cms-compose#3]
**Operating System**
- MacOSX 10.14.1 (18B75)

**Problem**
After cloning this repository and renaming
`docker-compose.override.example.yml`
to
`docker-compose.override.yml`
and replacing the license key
command ```$ docker-compose up``` causes `ERROR: The Compose file is invalid because: Service tomcat has neither an image nor a build context specified. At least one must be provided.` in bash.

**Suggested solution**
Remove entry "tomcat" from https://github.com/gentics/cms-compose/blob/master/docker-compose.override.example.yml

**Comment by berni2288** [comment]
Hey there!

Thanks for reporting this issue.
The problem is now solved with https://github.com/gentics/cms-compose/commit/4fa70d032d65f0a116bb44ecf1087c552c06d81b
